CREATE DATABASE TRUSTLY;
 
CREATE TABLE TRUSTLY.REPOSITORY
(
	ID 		int AUTO_INCREMENT PRIMARY KEY,
    EXTENSION varchar(50),
	TOTAL_LINES   int,
	TOTAL_BYTES   numeric(10,4),
    URL_REPOSITORY	varchar(200)
);

COMMIT;
